---
#
# Ansible managed
#
language: python

python:
  - "3.7"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    - image="amazonlinux" tag="1"
    - image="amazonlinux" tag="latest"
    - image="alpine" tag="latest"
    - image="alpine" tag="edge"
    - image="debian" tag="latest"
    - image="centos" tag="7"
    - image="centos" tag="latest"
    - image="fedora" tag="30"
    - image="fedora" tag="latest"
    - image="fedora" tag="rawhide"
    - image="opensuse" tag="latest"
    - image="ubuntu" tag="latest"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "R5Ee/D79DwIVvdXumBwybPIfeTS41BjQBSezGUGlYAH2ur3zzeJ6mK4ytNUEzbqAbNvci5I8yEI3BJCLCNSEyzKHc50s2wyxhlSGGplDzUSb0Nloy338o3z5cA0pjm7pRgEmO9zsaUXgCuqRUwp1u0HbhTYmVVgCN/Jz1QBfrH5xqocvwH/JaaZvJBwBwfzhG7j7kyZ06O2aS5fBPpAZrMtBlcVyIaeZTqpaaaGGA9AoUMd2L8BL/wwvDpubJuaki6836AqPjv2V4nPZMnLe3nR6ORaCCwfEPsI8WpXQEr43e2clnIrvwHqvc6igp/y/QUn/6x4QvJAy5V6TpUHWVYOHqF2em7WeQZqspWvdY4U0R5VI6iCBh3Xv/2T2zmLU5yIS2Mb3YRBjrvMVd41OwyOCZdEbhbcW/uxGgzeIHgn6AXaQgw5TEQmwMqRIBra4pxCfvENAVku06Y09ZIHoXJMtLjHTIKc1Msk0XRjOKr6T/Gay+81d3gkgOwd1X3OcAPFB5mL1YnfBsClv+mgLrVsDN2IRu/NC8DX/QHgKlSucx5oFb9ep40+0Mv3WZ/7kv3PDuIpBb1Q8dre28R+0s7R65lmrfKsfX73F0jwaaBRHRJlP9M0Hi/yobkIBDB8kbVllu5FCrFAE1KUJr4HuPu470DGTv0GFaPfo14F+hQA="
  email: false
