---
# tasks file for cve_2018_19788

- name: Create user
  ansible.builtin.user:
    name: cve_2018_19788
    uid: 2147483659
    state: present
  failed_when: no

- name: Execute a systemctl command as that user
  ansible.builtin.service:
    name: atd
    state: started
  become: yes
  become_user: cve_2018_19788
  register: cve_2018_19788_execute_user
  failed_when: no

- name: Test if user can manage service
  ansible.builtin.assert:
    that:
      - not cve_2018_19788_execute_user.changed
    msg: "users can manage services"
