---
# tasks file for cve_2018_19788
- name: create user
  user:
    name: cve_2018_19788
    uid: "{{ cve_2018_19788_uid }}"
    state: present
  notify:
    - remove user

- name: execute a systemctl command as root
  service:
    name: atd
    state: started
  register: execute_root
  notify:
    - stop service

- name: execute a systemctl command as that user
  service:
    name: atd
    state: stopped
  become: yes
  become_user: cve_2018_19788
  register: execute_user
  notify:
    - start service
  ignore_errors: yes

- name: clean up
  meta: flush_handlers

- name: test if user can manage service
  assert:
    that:
      - not execute_root.failed
      - not execute_user.changed
    msg: "users can manage services"
