---
# tasks file for cve_2018_19788
- name: create user
  user:
    name: cve_2018_19788
    uid: "{{ cve_2018_19788_uid }}"
    state: present
  notify:
    - remove user

- name: execute a systemctl command as root
  service:
    name: "{{ cve_2018_19788_service }}"
    state: started
  register: execute_root
  notify:
    - stop service

- name: execute a systemctl command as that user
  service:
    name: "{{ cve_2018_19788_service }}"
    state: stopped
  become: yes
  become_user: cve_2018_19788
  register: execute_user
  notify:
    - start service
  failed_when: no

- name: test if user can manage service
  assert:
    that:
      - execute_user is changed
    msg: "users can manage services"
