---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: cve_2018_19788-debian-unstable
    image: debian:unstable
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        cve_2018_19788_ignore_docker: no
  lint:
    name: ansible-lint
scenario:
  name: debian-unstable
verifier:
  name: goss
  lint:
    name: yamllint
